name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  delete:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files and folders to S3 bucket
        run: |
          GITHUB_FILES=$(find . -type f -not -path '*/\.*')
          GITHUB_FOLDERS=$(find . -type d -not -path '*/\.*')

          # Sync files
          for file in $GITHUB_FILES; do
            FILE_PATH=$(dirname "$file")
            FILE_NAME=$(basename "$file")
            if aws s3api head-object --bucket yes1 --key "$FILE_NAME" >/dev/null 2>&1; then
              aws s3 cp "$file" "s3://yes1/$FILE_NAME"
            else
              echo "Skipping $file: File does not exist in S3"
            fi
          done

          # Sync folders
          for folder in $GITHUB_FOLDERS; do
            if aws s3api head-object --bucket yes1 --key "$folder/" >/dev/null 2>&1; then
              aws s3 sync "./$folder" "s3://yes1/$folder"
            else
              echo "Skipping $folder: Folder does not exist in S3"
            fi
          done
