name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  delete:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files and folders to S3 bucket
        run: |
          GITHUB_FILES=$(find . -type f -not -path '*/\.*')
          GITHUB_FOLDERS=$(find . -type d -not -path '*/\.*')
          S3_FILES=$(aws s3 ls s3://yes1 --recursive | awk '{ print $NF }')
          S3_FOLDERS=$(aws s3 ls s3://yes1 --recursive | awk -F"/" '{ print $1 }' | uniq)

          # Sync files
          for file in $GITHUB_FILES; do
            FILE_PATH=$(dirname "$file")
            FILE_NAME=$(basename "$file")
            if echo "$S3_FILES" | grep -q -w "$FILE_PATH/$FILE_NAME"; then
              if [ "$FILE_PATH" = "." ]; then
                aws s3 cp "$file" "s3://yes1/$FILE_NAME"
              else
                aws s3 cp "$file" "s3://yes1/$FILE_PATH/$FILE_NAME"
              fi
            elif echo "$S3_FILES" | grep -q -w "$FILE_NAME"; then
              aws s3 mv "s3://yes1/$FILE_NAME" "s3://yes1/$FILE_PATH/$FILE_NAME"
              aws s3 cp "$file" "s3://yes1/$FILE_PATH/$FILE_NAME"
            else
              echo "Skipping $file: File doesn't exist in S3"
            fi
          done

          # Sync folders
          for folder in $GITHUB_FOLDERS; do
            if echo "$S3_FOLDERS" | grep -q -w "$folder"; then
              aws s3 sync "./$folder" "s3://yes1/$folder"
            else
              echo "Skipping $folder: Folder doesn't exist in S3"
            fi
          done
